import { create } from 'zustand';

interface AudioState {
  currentTrackIndex: number;
  isPlaying: boolean;
  volume: number;
  tracks: { name: string; url: string }[];
  setCurrentTrackIndex: (index: number) => void;
  setIsPlaying: (isPlaying: boolean) => void;
  setVolume: (volume: number) => void;
  setTracks: (tracks: { name: string; url: string }[]) => void;
}

export const useAudioStore = create<AudioState>((set) => ({
  currentTrackIndex: 0,
  isPlaying: false,
  volume: 50,
  tracks: [
    { name: 'The Sound of Rain', url: '/audio/001 - The Sound of Rain.webm' },
    { name: 'Eden', url: '/audio/002 - Eden.webm' },
    { name: 'Yal!X - Crystal Realm', url: '/audio/003 - Yal!X - Crystal Realm.webm' },
    { name: 'Descent', url: '/audio/004 - Descent.webm' },
    { name: 'The World Can Wait (feat. Yal!x)', url: '/audio/005 - The World Can Wait (feat. Yal!x).webm' },
    { name: 'Azimuth (feat. Leumas)', url: '/audio/006 - Azimuth (feat. Leumas).webm' },
    { name: 'Lantau', url: '/audio/007 - Lantau.webm' },
    { name: 'Discovery', url: '/audio/008 - Discovery.webm' },
    { name: 'Overflow', url: '/audio/009 - Overflow.webm' },
    { name: 'Afterglow', url: '/audio/010 - Afterglow.webm' },
    { name: 'Loren', url: '/audio/011 - Loren.webm' },
    { name: "Can't Find My Way", url: "/audio/012 - Can't Find My Way.webm" },
    { name: 'Unfold', url: '/audio/013 - Unfold.webm' },
    { name: 'Duality', url: '/audio/014 - Duality.webm' },
    { name: 'Waiting For Nightfall', url: '/audio/015 - Waiting For Nightfall.webm' },
    { name: 'Forever Waiting', url: '/audio/016 - Forever Waiting.webm' },
    { name: 'Last Hope', url: '/audio/017 - Last Hope.webm' },
    { name: 'The Dark of My Soul', url: '/audio/018 - The Dark of My Soul.webm' },
    { name: 'Sunflowers', url: '/audio/019 - Sunflowers.webm' },
    { name: 'Everything Changes', url: '/audio/020 - Everything Changes.webm' },
    { name: 'Breathe In', url: '/audio/021 - Breathe In.webm' },
    { name: 'Night Passage', url: '/audio/022 - Night Passage.webm' },
    { name: 'In Our Hands', url: '/audio/023 - In Our Hands.webm' },
    { name: 'The Way You', url: '/audio/024 - The Way You.webm' },
    { name: "I'll be there With You", url: "/audio/025 - I'll be there With You.webm" },
    { name: 'View from Above', url: '/audio/026 - View from Above.webm' },
    { name: 'Dusk', url: '/audio/027 - Dusk.webm' },
    { name: 'Dreamless', url: '/audio/028 - Dreamless.webm' },
    { name: 'I Still Hold On', url: '/audio/029 - I Still Hold On.webm' },
    { name: 'What If You Fly？', url: '/audio/030 - What If You Fly？.webm' },
    { name: 'Starlit Meadows', url: '/audio/031 - Starlit Meadows.webm' },
    { name: 'Lifeline', url: '/audio/032 - Lifeline.webm' },
    { name: 'Full of Life', url: '/audio/033 - Full of Life.webm' },
    { name: 'Maybe In Another Life', url: '/audio/034 - Maybe In Another Life.webm' },
    { name: 'Need You To Stay', url: '/audio/035 - Need You To Stay.webm' },
    { name: 'Dawn', url: '/audio/036 - Dawn.webm' },
    { name: 'One Day', url: '/audio/037 - One Day.webm' },
    { name: 'Spearmint', url: '/audio/038 - Spearmint.webm' },
    { name: 'Stellar', url: '/audio/039 - Stellar.webm' },
    { name: 'Solicity', url: '/audio/040 - Solicity.webm' },
    { name: 'Passion (DAY 7 Remix)', url: '/audio/042 - Passion (DAY 7 Remix).webm' },
    { name: 'René', url: '/audio/043 - René.webm' },
    { name: 'Waiting for a Sign', url: '/audio/044 - Waiting for a Sign.webm' },
    { name: 'Regret', url: '/audio/045 - Regret.webm' },
    { name: 'Ethereal', url: '/audio/046 - Ethereal.webm' },
    { name: 'Sleepless', url: '/audio/047 - Sleepless.webm' },
    { name: 'Through Silence', url: '/audio/048 - Through Silence.webm' },
    { name: 'Living In Shadow (feat. Oscuro)', url: '/audio/049 - Living In Shadow (feat. Oscuro).webm' },
    { name: 'Nova', url: '/audio/050 - Nova.webm' },
    { name: 'Lost in Myself', url: '/audio/051 - Lost in Myself.webm' },
    { name: 'Everything Matters', url: '/audio/052 - Everything Matters.webm' },
    { name: 'Under The Surface', url: '/audio/053 - Under The Surface.webm' },
    { name: 'Panorama', url: '/audio/054 - Panorama.webm' },
    { name: 'Moxie', url: '/audio/055 - Moxie.webm' },
    { name: 'Those micro rhythms in my head remind me of you', url: '/audio/056 - Those micro rhythms in my head remind me of you.webm' },
    { name: 'Never Be', url: '/audio/057 - Never Be.webm' },
    { name: 'Slow Mornings', url: '/audio/058 - Slow Mornings.webm' },
    { name: 'Slowly to the Sun', url: '/audio/059 - Slowly to the Sun.webm' },
    { name: 'Cosmos', url: '/audio/060 - Cosmos.webm' },
    { name: 'Beaming Hearts', url: '/audio/061 - Beaming Hearts.webm' },
    { name: 'Moments Wash Ashore', url: '/audio/062 - Moments Wash Ashore.webm' },
    { name: 'Vision', url: '/audio/063 - Vision.webm' },
    { name: 'In The End (Chill Mix)', url: '/audio/064 - In The End (Chill Mix).webm' },
    { name: 'PLEASE COME HOME', url: '/audio/065 - PLEASE COME HOME.webm' },
    { name: 'The Alchemist', url: '/audio/066 - The Alchemist.webm' },
    { name: 'site of grace', url: '/audio/067 - site of grace.webm' },
    { name: 'Left Alone', url: '/audio/068 - Left Alone.webm' },
    { name: 'Inside Our Hearts', url: '/audio/069 - Inside Our Hearts.webm' },
    { name: 'Paradise Lost', url: '/audio/070 - Paradise Lost.webm' },
    { name: 'Hope', url: '/audio/071 - Hope.webm' },
    { name: 'Secret Sanctuary', url: '/audio/072 - Secret Sanctuary.webm' },
    { name: 'Moments', url: '/audio/073 - Moments.webm' },
    { name: 'Stay', url: '/audio/074 - Stay.webm' },
    { name: 'Anxiety', url: '/audio/075 - Anxiety.webm' },
    { name: 'LOOK THE OTHER WAY', url: '/audio/076 - LOOK THE OTHER WAY.webm' },
    { name: 'Only You', url: '/audio/077 - Only You.webm' },
    { name: 'Ataraxia', url: '/audio/078 - Ataraxia.webm' },
    { name: 'Nomad', url: '/audio/079 - Nomad.webm' },
    { name: 'Fantasia', url: '/audio/080 - Fantasia.webm' },
    { name: 'Reconnect', url: '/audio/081 - Reconnect.webm' },
    { name: 'Until We Meet Again', url: '/audio/082 - Until We Meet Again.webm' },
    { name: 'Obsessed', url: '/audio/083 - Obsessed.webm' },
    { name: 'Essence', url: '/audio/084 - Essence.webm' },
    { name: 'For a Brief Moment (Extended Version)', url: '/audio/085 - For a Brief Moment (Extended Version).webm' },
    { name: 'Landfall', url: '/audio/086 - Landfall.webm' },
    { name: 'Runaway', url: '/audio/087 - Runaway.webm' },
    { name: 'Dreamscape', url: '/audio/088 - Dreamscape.webm' },
    { name: 'Loneliness', url: '/audio/089 - Loneliness.webm' },
    { name: 'Painless', url: '/audio/090 - Painless.webm' },
    { name: 'Sacred Nights', url: '/audio/091 - Sacred Nights.webm' },
    { name: 'Untitled', url: '/audio/092 - Untitled.webm' },
    { name: 'Emerald Forest', url: '/audio/093 - Emerald Forest.webm' },
    { name: 'Yui', url: '/audio/094 - Yui.webm' },
    { name: 'Something New', url: '/audio/095 - Something New.webm' },
    { name: 'Vertigo (feat. Amethyst)', url: '/audio/096 - Vertigo (feat. Amethyst).webm' },
    { name: 'Elegiac', url: '/audio/097 - Elegiac.webm' },
    { name: 'Mist', url: '/audio/098 - Mist.webm' },
    { name: "While You're Gone", url: "/audio/099 - While You're Gone.webm" },
    { name: 'Rebirth', url: '/audio/100 - Rebirth.webm' },
    { name: 'Evil Beauty', url: '/audio/101 - Evil Beauty.webm' },
    { name: "Life's so Short", url: "/audio/102 - Life's so Short.webm" },
    { name: 'You Take Me Down', url: '/audio/103 - You Take Me Down.webm' },
    { name: 'Fractured Thoughts', url: '/audio/104 - Fractured Thoughts.webm' },
    { name: 'Area of Solace', url: '/audio/105 - Area of Solace.webm' },
    { name: 'Memory Lane', url: '/audio/106 - Memory Lane.webm' },
    { name: 'Silence.', url: '/audio/108 - Silence..webm' },
    { name: 'Unrevolve', url: '/audio/109 - Unrevolve.webm' },
    { name: 'Apparitions', url: '/audio/110 - Apparitions.webm' },
    { name: 'Reflection', url: '/audio/111 - Reflection.webm' },
    { name: 'Solitude', url: '/audio/112 - Solitude.webm' },
    { name: 'Emotional Tourism', url: '/audio/113 - Emotional Tourism.webm' },
    { name: 'Nothing Else', url: '/audio/114 - Nothing Else.webm' },
    { name: 'PART OF ME.', url: '/audio/115 - PART OF ME..webm' },
    { name: 'Change', url: '/audio/116 - Change.webm' },
    { name: 'All I Had', url: '/audio/117 - All I Had.webm' },
    { name: 'Luca Francini - Sidereal', url: '/audio/118 - Luca Francini - Sidereal.webm' },
    { name: 'Something, Everything', url: '/audio/119 - Something, Everything.webm' },
    { name: 'Sarajevo (Blackmill Remix)', url: '/audio/120 - Sarajevo (Blackmill Remix).webm' },
    { name: 'Piano', url: '/audio/121 - Piano.webm' },
    { name: 'Promises', url: '/audio/122 - Promises.webm' },
    { name: "You're Not Alone", url: "/audio/123 - You're Not Alone.webm" },
    { name: 'Frozen in Time', url: '/audio/124 - Frozen in Time.webm' },
    { name: 'Devotion', url: '/audio/125 - Devotion.webm' },
    { name: 'Falling Down', url: '/audio/126 - Falling Down.webm' },
    { name: 'Fragments Of The Past', url: '/audio/127 - Fragments Of The Past.webm' },
    { name: 'Hollowing', url: '/audio/128 - Hollowing.webm' },
    { name: 'Sitting on the Moon', url: '/audio/129 - Sitting on the Moon.webm' },
    { name: 'Fragmented Past', url: '/audio/130 - Fragmented Past.webm' },
    { name: 'Dreams', url: '/audio/131 - Dreams.webm' },
    { name: 'Nocturne', url: '/audio/132 - Nocturne.webm' },
    { name: 'Something Tells Me', url: '/audio/133 - Something Tells Me.webm' },
    { name: 'Solarity', url: '/audio/134 - Solarity.webm' },
    { name: 'Save Me', url: '/audio/135 - Save Me.webm' },
    { name: 'Cycle', url: '/audio/136 - Cycle.webm' },
    { name: 'Lost in thoughts', url: '/audio/137 - Lost in thoughts.webm' },
    { name: 'FALLING', url: '/audio/138 - FALLING.webm' },
    { name: 'Twilight', url: '/audio/139 - Twilight.webm' },
    { name: 'Do You Think Of Me？', url: '/audio/140 - Do You Think Of Me？.webm' },
    { name: 'Elizabeth', url: '/audio/141 - Elizabeth.webm' },
    { name: 'Aurora', url: '/audio/142 - Aurora.webm' },
    { name: 'What Awaits Us', url: '/audio/143 - What Awaits Us.webm' },
    { name: 'Rain', url: '/audio/144 - Rain.webm' },
    { name: 'An Altered State', url: '/audio/145 - An Altered State.webm' },
    { name: 'Hold On', url: '/audio/146 - Hold On.webm' },
    { name: 'Iridescent', url: '/audio/147 - Iridescent.webm' },
    { name: 'Moonlit Lover', url: '/audio/148 - Moonlit Lover.webm' },
    { name: 'Remnants Of Us', url: '/audio/149 - Remnants Of Us.webm' },
    { name: 'Fall in Love', url: '/audio/150 - Fall in Love.webm' },
    { name: 'Falling Hopes', url: '/audio/151 - Falling Hopes.webm' },
    { name: 'Out Of Sight', url: '/audio/152 - Out Of Sight.webm' },
    { name: 'Eshonai', url: '/audio/153 - Eshonai.webm' },
    { name: 'Bloom', url: '/audio/154 - Bloom.webm' },
    { name: 'Dive', url: '/audio/155 - Dive.webm' },
    { name: 'Thinking of You (feat. Shura)', url: '/audio/156 - Thinking of You (feat. Shura).webm' },
    { name: 'Sanctuary', url: '/audio/157 - Sanctuary.webm' },
    { name: 'Her Melancholy', url: '/audio/158 - Her Melancholy.webm' },
    { name: 'Seclusion', url: '/audio/159 - Seclusion.webm' },
    { name: 'Serotonin (Radio Mix)', url: '/audio/160 - Serotonin (Radio Mix).webm' },
    { name: 'Forgive Me Now', url: '/audio/161 - Forgive Me Now.webm' },
    { name: 'Southern Forest', url: '/audio/162 - Southern Forest.webm' },
    { name: 'Reverence', url: '/audio/163 - Reverence.webm' },
    { name: 'Two Ways', url: '/audio/164 - Two Ways.webm' },
    { name: 'Alps (Original Mix)', url: '/audio/165 - Alps (Original Mix).webm' },
    { name: 'A Moment Before', url: '/audio/166 - A Moment Before.webm' },
    { name: 'Overcoming', url: '/audio/167 - Overcoming.webm' },
    { name: 'Those Days...', url: '/audio/168 - Those Days....webm' },
    { name: 'Tides', url: '/audio/169 - Tides.webm' },
    { name: 'Sleepless Nights', url: '/audio/170 - Sleepless Nights.webm' },
    { name: 'Our Dawn', url: '/audio/171 - Our Dawn.webm' },
    { name: 'All This Time', url: '/audio/172 - All This Time.webm' },
    { name: 'Elevate', url: '/audio/173 - Elevate.webm' },
    { name: 'Reaching For The Stars', url: '/audio/174 - Reaching For The Stars.webm' },
    { name: 'Solitude', url: '/audio/175 - Solitude.webm' },
    { name: 'Overcast', url: '/audio/176 - Overcast.webm' },
    { name: 'Mysteria', url: '/audio/177 - Mysteria.webm' },
    { name: 'Away', url: '/audio/178 - Away.webm' },
    { name: 'Tomorrow', url: '/audio/179 - Tomorrow.webm' },
    { name: 'Skypath', url: '/audio/180 - Skypath.webm' },
    { name: 'Through the Silence', url: '/audio/181 - Through the Silence.webm' },
    { name: 'Fragments', url: '/audio/182 - Fragments.webm' },
  ],
  setCurrentTrackIndex: (index) => set({ currentTrackIndex: index }),
  setIsPlaying: (isPlaying) => set({ isPlaying: isPlaying }),
  setVolume: (volume) => set({ volume: volume }),
  setTracks: (tracks) => set({ tracks }),
}));